import 'source-map-support/register'
import {
  type BaseAttrs,
  type Bindings,
  type Data,
  DerogMode,
  type DeviceData,
  type DevicePostData,
  type DevicePostDataAny,
  type ErrorData,
  type FirstGenDevicePostData,
  type LoginCredentials,
  type LoginData,
  type LoginPostData,
  Mode,
  NUMBER_1,
  Switch,
} from './types'
import HeatzyAPI, {
  type APISettings,
  type Logger,
  type SettingManager,
} from './lib/HeatzyAPI'

export {
  HeatzyAPI as default,
  DerogMode,
  Mode,
  Switch,
  NUMBER_1,
  type APISettings,
  type BaseAttrs,
  type Bindings,
  type Data,
  type DeviceData,
  type DevicePostData,
  type DevicePostDataAny,
  type ErrorData,
  type FirstGenDevicePostData,
  type LoginCredentials,
  type LoginData,
  type LoginPostData,
  type Logger,
  type SettingManager,
}
